// Auto-generated by LibreLane
module CNNver2(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  output CNNver2_MISO,
  input CNNver2_SPICLOCK_50,
  input CNNver2_SS_N,
  input CNNver2_MOSI
);
endmodule
