// Auto-generated by LibreLane
module user_project_example(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input clk_i,
  input rst_ni,
  input[16:0] ui_PAD2CORE,
  output[16:0] uo_CORE2PAD
);
endmodule
