/* Generated by Yosys 0.60 (git sha1 5bafeb77dc71e054fa331ab9efa613e6fb0a1c49, clang++ 21.1.2 -fPIC -O3) */

module user_project_example(clk_i, rst_ni, ui_PAD2CORE, uo_CORE2PAD);
  input clk_i;
  wire clk_i;
  input rst_ni;
  wire rst_ni;
  input [16:0] ui_PAD2CORE;
  wire [16:0] ui_PAD2CORE;
  output [16:0] uo_CORE2PAD;
  wire [16:0] uo_CORE2PAD;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire \spm_inst.csa0.hsum2 ;
  wire \spm_inst.csa0.sc ;
  wire \spm_inst.csa0.sum ;
  wire \spm_inst.csa0.y ;
  wire \spm_inst.genblk1[10].csa.hsum2 ;
  wire \spm_inst.genblk1[10].csa.sc ;
  wire \spm_inst.genblk1[10].csa.sum ;
  wire \spm_inst.genblk1[10].csa.y ;
  wire \spm_inst.genblk1[11].csa.hsum2 ;
  wire \spm_inst.genblk1[11].csa.sc ;
  wire \spm_inst.genblk1[11].csa.y ;
  wire \spm_inst.genblk1[12].csa.hsum2 ;
  wire \spm_inst.genblk1[12].csa.sc ;
  wire \spm_inst.genblk1[12].csa.y ;
  wire \spm_inst.genblk1[13].csa.hsum2 ;
  wire \spm_inst.genblk1[13].csa.sc ;
  wire \spm_inst.genblk1[13].csa.y ;
  wire \spm_inst.genblk1[14].csa.hsum2 ;
  wire \spm_inst.genblk1[14].csa.sc ;
  wire \spm_inst.genblk1[14].csa.y ;
  wire \spm_inst.genblk1[1].csa.hsum2 ;
  wire \spm_inst.genblk1[1].csa.sc ;
  wire \spm_inst.genblk1[1].csa.y ;
  wire \spm_inst.genblk1[2].csa.hsum2 ;
  wire \spm_inst.genblk1[2].csa.sc ;
  wire \spm_inst.genblk1[2].csa.y ;
  wire \spm_inst.genblk1[3].csa.hsum2 ;
  wire \spm_inst.genblk1[3].csa.sc ;
  wire \spm_inst.genblk1[3].csa.y ;
  wire \spm_inst.genblk1[4].csa.hsum2 ;
  wire \spm_inst.genblk1[4].csa.sc ;
  wire \spm_inst.genblk1[4].csa.y ;
  wire \spm_inst.genblk1[5].csa.hsum2 ;
  wire \spm_inst.genblk1[5].csa.sc ;
  wire \spm_inst.genblk1[5].csa.y ;
  wire \spm_inst.genblk1[6].csa.hsum2 ;
  wire \spm_inst.genblk1[6].csa.sc ;
  wire \spm_inst.genblk1[6].csa.y ;
  wire \spm_inst.genblk1[7].csa.hsum2 ;
  wire \spm_inst.genblk1[7].csa.sc ;
  wire \spm_inst.genblk1[7].csa.y ;
  wire \spm_inst.genblk1[8].csa.hsum2 ;
  wire \spm_inst.genblk1[8].csa.sc ;
  wire \spm_inst.genblk1[8].csa.y ;
  wire \spm_inst.genblk1[9].csa.hsum2 ;
  wire \spm_inst.genblk1[9].csa.sc ;
  wire \spm_inst.tcmp.z ;
  sg13g2_nand2_1 _078_ (
    .A(ui_PAD2CORE[0]),
    .B(ui_PAD2CORE[15]),
    .Y(_065_)
  );
  sg13g2_nand2_1 _079_ (
    .A(\spm_inst.genblk1[14].csa.sc ),
    .B(\spm_inst.genblk1[14].csa.y ),
    .Y(_066_)
  );
  sg13g2_nor2_1 _080_ (
    .A(\spm_inst.genblk1[14].csa.sc ),
    .B(\spm_inst.genblk1[14].csa.y ),
    .Y(_067_)
  );
  sg13g2_xor2_1 _081_ (
    .A(\spm_inst.genblk1[14].csa.sc ),
    .B(\spm_inst.genblk1[14].csa.y ),
    .X(_068_)
  );
  sg13g2_xnor2_1 _082_ (
    .A(_065_),
    .B(_068_),
    .Y(\spm_inst.genblk1[14].csa.hsum2 )
  );
  sg13g2_o21ai_1 _083_ (
    .A1(_065_),
    .A2(_067_),
    .B1(_066_),
    .Y(_005_)
  );
  sg13g2_nand2_1 _084_ (
    .A(ui_PAD2CORE[14]),
    .B(ui_PAD2CORE[0]),
    .Y(_069_)
  );
  sg13g2_nand2_1 _085_ (
    .A(\spm_inst.genblk1[13].csa.sc ),
    .B(\spm_inst.genblk1[13].csa.y ),
    .Y(_070_)
  );
  sg13g2_nor2_1 _086_ (
    .A(\spm_inst.genblk1[13].csa.sc ),
    .B(\spm_inst.genblk1[13].csa.y ),
    .Y(_071_)
  );
  sg13g2_xor2_1 _087_ (
    .A(\spm_inst.genblk1[13].csa.sc ),
    .B(\spm_inst.genblk1[13].csa.y ),
    .X(_072_)
  );
  sg13g2_xnor2_1 _088_ (
    .A(_069_),
    .B(_072_),
    .Y(\spm_inst.genblk1[13].csa.hsum2 )
  );
  sg13g2_o21ai_1 _089_ (
    .A1(_069_),
    .A2(_071_),
    .B1(_070_),
    .Y(_004_)
  );
  sg13g2_nand2_1 _090_ (
    .A(ui_PAD2CORE[0]),
    .B(ui_PAD2CORE[13]),
    .Y(_073_)
  );
  sg13g2_nand2_1 _091_ (
    .A(\spm_inst.genblk1[12].csa.sc ),
    .B(\spm_inst.genblk1[12].csa.y ),
    .Y(_074_)
  );
  sg13g2_nor2_1 _092_ (
    .A(\spm_inst.genblk1[12].csa.sc ),
    .B(\spm_inst.genblk1[12].csa.y ),
    .Y(_075_)
  );
  sg13g2_xor2_1 _093_ (
    .A(\spm_inst.genblk1[12].csa.sc ),
    .B(\spm_inst.genblk1[12].csa.y ),
    .X(_076_)
  );
  sg13g2_xnor2_1 _094_ (
    .A(_073_),
    .B(_076_),
    .Y(\spm_inst.genblk1[12].csa.hsum2 )
  );
  sg13g2_o21ai_1 _095_ (
    .A1(_073_),
    .A2(_075_),
    .B1(_074_),
    .Y(_003_)
  );
  sg13g2_nand2_1 _096_ (
    .A(ui_PAD2CORE[0]),
    .B(ui_PAD2CORE[12]),
    .Y(_077_)
  );
  sg13g2_nand2_1 _097_ (
    .A(\spm_inst.genblk1[11].csa.sc ),
    .B(\spm_inst.genblk1[11].csa.y ),
    .Y(_017_)
  );
  sg13g2_nor2_1 _098_ (
    .A(\spm_inst.genblk1[11].csa.sc ),
    .B(\spm_inst.genblk1[11].csa.y ),
    .Y(_018_)
  );
  sg13g2_xor2_1 _099_ (
    .A(\spm_inst.genblk1[11].csa.sc ),
    .B(\spm_inst.genblk1[11].csa.y ),
    .X(_019_)
  );
  sg13g2_xnor2_1 _100_ (
    .A(_077_),
    .B(_019_),
    .Y(\spm_inst.genblk1[11].csa.hsum2 )
  );
  sg13g2_o21ai_1 _101_ (
    .A1(_077_),
    .A2(_018_),
    .B1(_017_),
    .Y(_002_)
  );
  sg13g2_nand2_1 _102_ (
    .A(ui_PAD2CORE[0]),
    .B(ui_PAD2CORE[11]),
    .Y(_020_)
  );
  sg13g2_nand2_1 _103_ (
    .A(\spm_inst.genblk1[10].csa.sc ),
    .B(\spm_inst.genblk1[10].csa.y ),
    .Y(_021_)
  );
  sg13g2_nor2_1 _104_ (
    .A(\spm_inst.genblk1[10].csa.sc ),
    .B(\spm_inst.genblk1[10].csa.y ),
    .Y(_022_)
  );
  sg13g2_xor2_1 _105_ (
    .A(\spm_inst.genblk1[10].csa.sc ),
    .B(\spm_inst.genblk1[10].csa.y ),
    .X(_023_)
  );
  sg13g2_xnor2_1 _106_ (
    .A(_020_),
    .B(_023_),
    .Y(\spm_inst.genblk1[10].csa.hsum2 )
  );
  sg13g2_o21ai_1 _107_ (
    .A1(_020_),
    .A2(_022_),
    .B1(_021_),
    .Y(_001_)
  );
  sg13g2_nand2_1 _108_ (
    .A(ui_PAD2CORE[0]),
    .B(ui_PAD2CORE[10]),
    .Y(_024_)
  );
  sg13g2_nand2_1 _109_ (
    .A(\spm_inst.genblk1[9].csa.sc ),
    .B(\spm_inst.genblk1[10].csa.sum ),
    .Y(_025_)
  );
  sg13g2_nor2_1 _110_ (
    .A(\spm_inst.genblk1[9].csa.sc ),
    .B(\spm_inst.genblk1[10].csa.sum ),
    .Y(_026_)
  );
  sg13g2_xor2_1 _111_ (
    .A(\spm_inst.genblk1[9].csa.sc ),
    .B(\spm_inst.genblk1[10].csa.sum ),
    .X(_027_)
  );
  sg13g2_xnor2_1 _112_ (
    .A(_024_),
    .B(_027_),
    .Y(\spm_inst.genblk1[9].csa.hsum2 )
  );
  sg13g2_o21ai_1 _113_ (
    .A1(_024_),
    .A2(_026_),
    .B1(_025_),
    .Y(_014_)
  );
  sg13g2_nand2_1 _114_ (
    .A(ui_PAD2CORE[0]),
    .B(ui_PAD2CORE[9]),
    .Y(_028_)
  );
  sg13g2_nand2_1 _115_ (
    .A(\spm_inst.genblk1[8].csa.sc ),
    .B(\spm_inst.genblk1[8].csa.y ),
    .Y(_029_)
  );
  sg13g2_nor2_1 _116_ (
    .A(\spm_inst.genblk1[8].csa.sc ),
    .B(\spm_inst.genblk1[8].csa.y ),
    .Y(_030_)
  );
  sg13g2_xor2_1 _117_ (
    .A(\spm_inst.genblk1[8].csa.sc ),
    .B(\spm_inst.genblk1[8].csa.y ),
    .X(_031_)
  );
  sg13g2_xnor2_1 _118_ (
    .A(_028_),
    .B(_031_),
    .Y(\spm_inst.genblk1[8].csa.hsum2 )
  );
  sg13g2_o21ai_1 _119_ (
    .A1(_028_),
    .A2(_030_),
    .B1(_029_),
    .Y(_013_)
  );
  sg13g2_nand2_1 _120_ (
    .A(ui_PAD2CORE[0]),
    .B(ui_PAD2CORE[8]),
    .Y(_032_)
  );
  sg13g2_nand2_1 _121_ (
    .A(\spm_inst.genblk1[7].csa.sc ),
    .B(\spm_inst.genblk1[7].csa.y ),
    .Y(_033_)
  );
  sg13g2_nor2_1 _122_ (
    .A(\spm_inst.genblk1[7].csa.sc ),
    .B(\spm_inst.genblk1[7].csa.y ),
    .Y(_034_)
  );
  sg13g2_xor2_1 _123_ (
    .A(\spm_inst.genblk1[7].csa.sc ),
    .B(\spm_inst.genblk1[7].csa.y ),
    .X(_035_)
  );
  sg13g2_xnor2_1 _124_ (
    .A(_032_),
    .B(_035_),
    .Y(\spm_inst.genblk1[7].csa.hsum2 )
  );
  sg13g2_o21ai_1 _125_ (
    .A1(_032_),
    .A2(_034_),
    .B1(_033_),
    .Y(_012_)
  );
  sg13g2_nand2_1 _126_ (
    .A(ui_PAD2CORE[0]),
    .B(ui_PAD2CORE[7]),
    .Y(_036_)
  );
  sg13g2_nand2_1 _127_ (
    .A(\spm_inst.genblk1[6].csa.sc ),
    .B(\spm_inst.genblk1[6].csa.y ),
    .Y(_037_)
  );
  sg13g2_nor2_1 _128_ (
    .A(\spm_inst.genblk1[6].csa.sc ),
    .B(\spm_inst.genblk1[6].csa.y ),
    .Y(_038_)
  );
  sg13g2_xor2_1 _129_ (
    .A(\spm_inst.genblk1[6].csa.sc ),
    .B(\spm_inst.genblk1[6].csa.y ),
    .X(_039_)
  );
  sg13g2_xnor2_1 _130_ (
    .A(_036_),
    .B(_039_),
    .Y(\spm_inst.genblk1[6].csa.hsum2 )
  );
  sg13g2_o21ai_1 _131_ (
    .A1(_036_),
    .A2(_038_),
    .B1(_037_),
    .Y(_011_)
  );
  sg13g2_nand2_1 _132_ (
    .A(ui_PAD2CORE[0]),
    .B(ui_PAD2CORE[6]),
    .Y(_040_)
  );
  sg13g2_nand2_1 _133_ (
    .A(\spm_inst.genblk1[5].csa.sc ),
    .B(\spm_inst.genblk1[5].csa.y ),
    .Y(_041_)
  );
  sg13g2_nor2_1 _134_ (
    .A(\spm_inst.genblk1[5].csa.sc ),
    .B(\spm_inst.genblk1[5].csa.y ),
    .Y(_042_)
  );
  sg13g2_xor2_1 _135_ (
    .A(\spm_inst.genblk1[5].csa.sc ),
    .B(\spm_inst.genblk1[5].csa.y ),
    .X(_043_)
  );
  sg13g2_xnor2_1 _136_ (
    .A(_040_),
    .B(_043_),
    .Y(\spm_inst.genblk1[5].csa.hsum2 )
  );
  sg13g2_o21ai_1 _137_ (
    .A1(_040_),
    .A2(_042_),
    .B1(_041_),
    .Y(_010_)
  );
  sg13g2_nand2_1 _138_ (
    .A(ui_PAD2CORE[0]),
    .B(ui_PAD2CORE[5]),
    .Y(_044_)
  );
  sg13g2_nand2_1 _139_ (
    .A(\spm_inst.genblk1[4].csa.sc ),
    .B(\spm_inst.genblk1[4].csa.y ),
    .Y(_045_)
  );
  sg13g2_nor2_1 _140_ (
    .A(\spm_inst.genblk1[4].csa.sc ),
    .B(\spm_inst.genblk1[4].csa.y ),
    .Y(_046_)
  );
  sg13g2_xor2_1 _141_ (
    .A(\spm_inst.genblk1[4].csa.sc ),
    .B(\spm_inst.genblk1[4].csa.y ),
    .X(_047_)
  );
  sg13g2_xnor2_1 _142_ (
    .A(_044_),
    .B(_047_),
    .Y(\spm_inst.genblk1[4].csa.hsum2 )
  );
  sg13g2_o21ai_1 _143_ (
    .A1(_044_),
    .A2(_046_),
    .B1(_045_),
    .Y(_009_)
  );
  sg13g2_nand2_1 _144_ (
    .A(ui_PAD2CORE[0]),
    .B(ui_PAD2CORE[4]),
    .Y(_048_)
  );
  sg13g2_nand2_1 _145_ (
    .A(\spm_inst.genblk1[3].csa.sc ),
    .B(\spm_inst.genblk1[3].csa.y ),
    .Y(_049_)
  );
  sg13g2_nor2_1 _146_ (
    .A(\spm_inst.genblk1[3].csa.sc ),
    .B(\spm_inst.genblk1[3].csa.y ),
    .Y(_050_)
  );
  sg13g2_xor2_1 _147_ (
    .A(\spm_inst.genblk1[3].csa.sc ),
    .B(\spm_inst.genblk1[3].csa.y ),
    .X(_051_)
  );
  sg13g2_xnor2_1 _148_ (
    .A(_048_),
    .B(_051_),
    .Y(\spm_inst.genblk1[3].csa.hsum2 )
  );
  sg13g2_o21ai_1 _149_ (
    .A1(_048_),
    .A2(_050_),
    .B1(_049_),
    .Y(_008_)
  );
  sg13g2_nand2_1 _150_ (
    .A(ui_PAD2CORE[0]),
    .B(ui_PAD2CORE[3]),
    .Y(_052_)
  );
  sg13g2_nand2_1 _151_ (
    .A(\spm_inst.genblk1[2].csa.sc ),
    .B(\spm_inst.genblk1[2].csa.y ),
    .Y(_053_)
  );
  sg13g2_nor2_1 _152_ (
    .A(\spm_inst.genblk1[2].csa.sc ),
    .B(\spm_inst.genblk1[2].csa.y ),
    .Y(_054_)
  );
  sg13g2_xor2_1 _153_ (
    .A(\spm_inst.genblk1[2].csa.sc ),
    .B(\spm_inst.genblk1[2].csa.y ),
    .X(_055_)
  );
  sg13g2_xnor2_1 _154_ (
    .A(_052_),
    .B(_055_),
    .Y(\spm_inst.genblk1[2].csa.hsum2 )
  );
  sg13g2_o21ai_1 _155_ (
    .A1(_052_),
    .A2(_054_),
    .B1(_053_),
    .Y(_007_)
  );
  sg13g2_nand2_1 _156_ (
    .A(ui_PAD2CORE[0]),
    .B(ui_PAD2CORE[2]),
    .Y(_056_)
  );
  sg13g2_nand2_1 _157_ (
    .A(\spm_inst.genblk1[1].csa.sc ),
    .B(\spm_inst.genblk1[1].csa.y ),
    .Y(_057_)
  );
  sg13g2_nor2_1 _158_ (
    .A(\spm_inst.genblk1[1].csa.sc ),
    .B(\spm_inst.genblk1[1].csa.y ),
    .Y(_058_)
  );
  sg13g2_xor2_1 _159_ (
    .A(\spm_inst.genblk1[1].csa.sc ),
    .B(\spm_inst.genblk1[1].csa.y ),
    .X(_059_)
  );
  sg13g2_xnor2_1 _160_ (
    .A(_056_),
    .B(_059_),
    .Y(\spm_inst.genblk1[1].csa.hsum2 )
  );
  sg13g2_o21ai_1 _161_ (
    .A1(_056_),
    .A2(_058_),
    .B1(_057_),
    .Y(_006_)
  );
  sg13g2_nand2_1 _162_ (
    .A(ui_PAD2CORE[0]),
    .B(ui_PAD2CORE[16]),
    .Y(_060_)
  );
  sg13g2_nand2b_1 _163_ (
    .A_N(\spm_inst.tcmp.z ),
    .B(_060_),
    .Y(_016_)
  );
  sg13g2_xnor2_1 _164_ (
    .A(\spm_inst.tcmp.z ),
    .B(_060_),
    .Y(_015_)
  );
  sg13g2_nand2_1 _165_ (
    .A(ui_PAD2CORE[0]),
    .B(ui_PAD2CORE[1]),
    .Y(_061_)
  );
  sg13g2_nand2_1 _166_ (
    .A(\spm_inst.csa0.sc ),
    .B(\spm_inst.csa0.y ),
    .Y(_062_)
  );
  sg13g2_nor2_1 _167_ (
    .A(\spm_inst.csa0.sc ),
    .B(\spm_inst.csa0.y ),
    .Y(_063_)
  );
  sg13g2_xor2_1 _168_ (
    .A(\spm_inst.csa0.sc ),
    .B(\spm_inst.csa0.y ),
    .X(_064_)
  );
  sg13g2_xnor2_1 _169_ (
    .A(_061_),
    .B(_064_),
    .Y(\spm_inst.csa0.hsum2 )
  );
  sg13g2_o21ai_1 _170_ (
    .A1(_061_),
    .A2(_063_),
    .B1(_062_),
    .Y(_000_)
  );
  sg13g2_dfrbpq_1 _171_ (
    .CLK(clk_i),
    .D(_005_),
    .Q(\spm_inst.genblk1[14].csa.sc ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _172_ (
    .CLK(clk_i),
    .D(\spm_inst.genblk1[14].csa.hsum2 ),
    .Q(\spm_inst.genblk1[13].csa.y ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _173_ (
    .CLK(clk_i),
    .D(_004_),
    .Q(\spm_inst.genblk1[13].csa.sc ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _174_ (
    .CLK(clk_i),
    .D(\spm_inst.genblk1[13].csa.hsum2 ),
    .Q(\spm_inst.genblk1[12].csa.y ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _175_ (
    .CLK(clk_i),
    .D(_003_),
    .Q(\spm_inst.genblk1[12].csa.sc ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _176_ (
    .CLK(clk_i),
    .D(\spm_inst.genblk1[12].csa.hsum2 ),
    .Q(\spm_inst.genblk1[11].csa.y ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _177_ (
    .CLK(clk_i),
    .D(_002_),
    .Q(\spm_inst.genblk1[11].csa.sc ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _178_ (
    .CLK(clk_i),
    .D(\spm_inst.genblk1[11].csa.hsum2 ),
    .Q(\spm_inst.genblk1[10].csa.y ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _179_ (
    .CLK(clk_i),
    .D(_001_),
    .Q(\spm_inst.genblk1[10].csa.sc ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _180_ (
    .CLK(clk_i),
    .D(\spm_inst.genblk1[10].csa.hsum2 ),
    .Q(\spm_inst.genblk1[10].csa.sum ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _181_ (
    .CLK(clk_i),
    .D(_014_),
    .Q(\spm_inst.genblk1[9].csa.sc ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _182_ (
    .CLK(clk_i),
    .D(\spm_inst.genblk1[9].csa.hsum2 ),
    .Q(\spm_inst.genblk1[8].csa.y ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _183_ (
    .CLK(clk_i),
    .D(_013_),
    .Q(\spm_inst.genblk1[8].csa.sc ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _184_ (
    .CLK(clk_i),
    .D(\spm_inst.genblk1[8].csa.hsum2 ),
    .Q(\spm_inst.genblk1[7].csa.y ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _185_ (
    .CLK(clk_i),
    .D(_012_),
    .Q(\spm_inst.genblk1[7].csa.sc ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _186_ (
    .CLK(clk_i),
    .D(\spm_inst.genblk1[7].csa.hsum2 ),
    .Q(\spm_inst.genblk1[6].csa.y ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _187_ (
    .CLK(clk_i),
    .D(_011_),
    .Q(\spm_inst.genblk1[6].csa.sc ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _188_ (
    .CLK(clk_i),
    .D(\spm_inst.genblk1[6].csa.hsum2 ),
    .Q(\spm_inst.genblk1[5].csa.y ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _189_ (
    .CLK(clk_i),
    .D(_010_),
    .Q(\spm_inst.genblk1[5].csa.sc ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _190_ (
    .CLK(clk_i),
    .D(\spm_inst.genblk1[5].csa.hsum2 ),
    .Q(\spm_inst.genblk1[4].csa.y ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _191_ (
    .CLK(clk_i),
    .D(_009_),
    .Q(\spm_inst.genblk1[4].csa.sc ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _192_ (
    .CLK(clk_i),
    .D(\spm_inst.genblk1[4].csa.hsum2 ),
    .Q(\spm_inst.genblk1[3].csa.y ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _193_ (
    .CLK(clk_i),
    .D(_008_),
    .Q(\spm_inst.genblk1[3].csa.sc ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _194_ (
    .CLK(clk_i),
    .D(\spm_inst.genblk1[3].csa.hsum2 ),
    .Q(\spm_inst.genblk1[2].csa.y ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _195_ (
    .CLK(clk_i),
    .D(_007_),
    .Q(\spm_inst.genblk1[2].csa.sc ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _196_ (
    .CLK(clk_i),
    .D(\spm_inst.genblk1[2].csa.hsum2 ),
    .Q(\spm_inst.genblk1[1].csa.y ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _197_ (
    .CLK(clk_i),
    .D(_006_),
    .Q(\spm_inst.genblk1[1].csa.sc ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _198_ (
    .CLK(clk_i),
    .D(\spm_inst.genblk1[1].csa.hsum2 ),
    .Q(\spm_inst.csa0.y ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _199_ (
    .CLK(clk_i),
    .D(_015_),
    .Q(\spm_inst.genblk1[14].csa.y ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _200_ (
    .CLK(clk_i),
    .D(_016_),
    .Q(\spm_inst.tcmp.z ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _201_ (
    .CLK(clk_i),
    .D(_000_),
    .Q(\spm_inst.csa0.sc ),
    .RESET_B(rst_ni)
  );
  sg13g2_dfrbpq_1 _202_ (
    .CLK(clk_i),
    .D(\spm_inst.csa0.hsum2 ),
    .Q(\spm_inst.csa0.sum ),
    .RESET_B(rst_ni)
  );
  sg13g2_tiehi _203_ (
    .L_HI(uo_CORE2PAD[1])
  );
  sg13g2_tielo _204_ (
    .L_LO(uo_CORE2PAD[2])
  );
  sg13g2_tielo _205_ (
    .L_LO(uo_CORE2PAD[3])
  );
  sg13g2_tielo _206_ (
    .L_LO(uo_CORE2PAD[4])
  );
  sg13g2_tielo _207_ (
    .L_LO(uo_CORE2PAD[5])
  );
  sg13g2_tielo _208_ (
    .L_LO(uo_CORE2PAD[6])
  );
  sg13g2_tielo _209_ (
    .L_LO(uo_CORE2PAD[7])
  );
  sg13g2_tielo _210_ (
    .L_LO(uo_CORE2PAD[8])
  );
  sg13g2_tielo _211_ (
    .L_LO(uo_CORE2PAD[9])
  );
  sg13g2_tielo _212_ (
    .L_LO(uo_CORE2PAD[10])
  );
  sg13g2_tielo _213_ (
    .L_LO(uo_CORE2PAD[11])
  );
  sg13g2_tielo _214_ (
    .L_LO(uo_CORE2PAD[12])
  );
  sg13g2_tielo _215_ (
    .L_LO(uo_CORE2PAD[13])
  );
  sg13g2_tielo _216_ (
    .L_LO(uo_CORE2PAD[14])
  );
  sg13g2_tielo _217_ (
    .L_LO(uo_CORE2PAD[15])
  );
  sg13g2_tielo _218_ (
    .L_LO(uo_CORE2PAD[16])
  );
  sg13g2_buf_1 _219_ (
    .A(\spm_inst.csa0.sum ),
    .X(uo_CORE2PAD[0])
  );
endmodule
